---
- apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  become: yes

- apt_repository: repo='deb http://pkg.jenkins-ci.org/debian-stable binary/'
  become: yes

- apt: name=jenkins update_cache=yes cache_valid_time=300 state=latest
  become: yes

- apt: name=nginx update_cache=yes cache_valid_time=300 state=latest
  become: yes

- file: path=/etc/nginx/sites-enabled/default state=absent
  become: yes
  notify: nginx restart

- template: src=jenkins.j2 dest=/etc/nginx/sites-available/jenkins
  become: yes
  notify: nginx restart

- file: src=/etc/nginx/sites-available/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link
  become: yes
  notify: nginx restart

- user: name=jenkins generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
